[[plugins]]
package = "netlify-plugin-nimbella"

[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "npm build"
  publish = "dist"

[context.deploy-preview]
  command = "npm build:preview"

[nimbella] 
  functions = "functions"